### ISSUE TITLE
Deprecated follow/unfollow API

### ISSUE THREAD

**Issue by DmitriyFrogo** [AndreyAsadchy/Xtra#29]
At the end of july, Twitch removed ability to follow/unfollow channels by API
Maybe necessary to remove this feature from Xtra, because "heart button" do nothing now

Info:
https://discuss.dev.twitch.tv/t/deprecation-of-create-and-delete-follows-api-endpoints/32351

**Comment by AndreyAsadchy** [comment]
Implemented in the fork
